# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: imagick
    resolvers:
        default:
            web_path: ~
    loaders:
        default:
            filesystem:
                data_root:
                    - '%upload_dir%'
    filter_sets:
        cache : ~
        xl:
            quality: 80
            format: webp
            filters:
                auto_rotate: ~
                #background : { color : '#ffffff' }
                downscale:
                    max: [1920, 1080]
        lg:
            quality: 80
            format: webp
            filters:
                auto_rotate: ~
                #background : { color : '#ffffff' }
                thumbnail: { size: [1440, 810], mode: inset }
        md:
            quality: 80
            format: webp
            filters:
                auto_rotate: ~
                #background : { color : '#ffffff' }
                thumbnail: { size: [800, 800], mode: inset }
        sm:
            quality: 80
            format: webp
            filters:
                auto_rotate: ~
                #background : { color : '#ffffff' }
                thumbnail: { size: [400, 400], mode: inset }
        xs:
            quality: 80
            format: webp
            filters:
                auto_rotate: ~
                #background : { color : '#ffffff' }
                thumbnail: { size: [100, 100], mode: inset }
        icon:
            quality: 80
            format: webp
            filters:
                auto_rotate: ~
                #background : { color : '#ffffff' }
                thumbnail: { size: [50, 50], mode: inset }